/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalInquiriesRouteImport } from './routes/portal.inquiries'
import { Route as PortalProductsRouteImport } from './routes/portal.products'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSkuRouteImport } from './routes/products.$sku'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalInquiriesRoute = PortalInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductsRoute = PortalProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsSkuRoute = ProductsSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => ProductsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/portal/inquiries': typeof PortalInquiriesRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/portal/inquiries': typeof PortalInquiriesRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/portal': typeof PortalIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/portal/inquiries': typeof PortalInquiriesRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/products/$sku': typeof ProductsSkuRoute
  '/portal/': typeof PortalIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/portal'
    | '/products'
    | '/portal/inquiries'
    | '/portal/products'
    | '/portal/settings'
    | '/products/$sku'
    | '/portal/'
    | '/products/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/portal/inquiries'
    | '/portal/products'
    | '/portal/settings'
    | '/products/$sku'
    | '/portal'
    | '/products'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/login'
    | '/portal'
    | '/products'
    | '/portal/inquiries'
    | '/portal/products'
    | '/portal/settings'
    | '/products/$sku'
    | '/portal/'
    | '/products/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/inquiries': {
      id: '/portal/inquiries'
      path: '/inquiries'
      fullPath: '/portal/inquiries'
      preLoaderRoute: typeof PortalInquiriesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/products': {
      id: '/portal/products'
      path: '/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalProductsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$sku': {
      id: '/products/$sku'
      path: '/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof ProductsSkuRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalInquiriesRoute: typeof PortalInquiriesRoute
  PortalProductsRoute: typeof PortalProductsRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalInquiriesRoute: PortalInquiriesRoute,
  PortalProductsRoute: PortalProductsRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProductsRouteChildren {
  ProductsSkuRoute: typeof ProductsSkuRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSkuRoute: ProductsSkuRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
